---

# updates check

- name: check for updates
  hosts: all

  tasks:
    - name: query for updates 
      yum:
        list: updates
      register: result

    - name: output results 
      debug:
        var: result.results

...

