---

# setup /etc/issue

- name: rm /etc/issue.net
  file:
    path: /etc/issue.net
    state: absent

- name: hard link /etc/issue.net to /etc/issue
  file:
    src: /etc/issue
    dest: /etc/issue.net
    state: hard

- name: install my warning in /etc/issue
  copy:
    src: files/issue.j2
    dest: /etc/issue
    force: yes
    owner: root
    group: root
    mode: 0644

...
