---

# update everything play

- name: update everything but the kernel
  yum:
    name: '*'
    state: latest
    exclude: kernel
  register: updates

- name: check for a kernel update?
  yum:
    list: updates
    update_only: yes
  register: kernel_update

- block:
  - name: update kernel
    yum:
      name: kernel
      state: latest
    notify: reboot
  when: kernel_update.results != []

- import_tasks: swinv.yaml
  when: updates.changed == true or kernel_update.results != []

...

